version: '3.8'

networks:
  minha_rede:

services:
  mysql:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: websiteInfo
      MYSQL_USER: database
      MYSQL_PASSWORD: senha123
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -uroot -proot ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./tabelas/consultores.sql:/docker-entrypoint-initdb.d/consultores.sql
      - ./tabelas/clientes.sql:/docker-entrypoint-initdb.d/clientes.sql
      - ./tabelas/imoveis.sql:/docker-entrypoint-initdb.d/imoveis.sql
      - ./tabelas/visitas.sql:/docker-entrypoint-initdb.d/visitas.sql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - minha_rede
    
  api:
    build: .
    container_name: node-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - minha_rede
    environment:
      - JWT_SECRET=imoveis-sa
